### ISSUE TITLE
Headers' time period not specified if week or month has been selected "cohort_period" 

### ISSUE THREAD

**Issue by andresbarreto** [FirstrockVC/lambdak#2]
modify headers to have correct input in 8-ball, from "activity_period" to "activity_week" or "activity_month", depending on if week or month was selected

**Comment by emetricz** [comment]
add headers based on:
colnames(data_5)<-c(paste("cohort_",period,sep=""),paste("activity_",period,sep=""),"users","revenue")

clean data if user_id is empty:
control for data_3<-filter(data_3, !is.na(user_id))
